scala_library(
  name = 'auth',
  dependencies = []
)

jvm_binary(
    name = 'main-bin',
    source = 'Application.scala',
    main="auth.Application",
    basename = 'hello-example',
    dependencies=[
        'src/main/scala/auth/Application'
    ]
)